version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - .env
    volumes:
      - app_data:/usr/src/app


volumes:
  app_data: